version: 1

sources:
  raw:
    tables:
      users:
        description: Raw user data
        columns:
          - name: user_id
            type: INTEGER
          - name: user_name
            type: VARCHAR
          - name: signup_date
            type: DATE

      events:
        description: Raw event data
        columns:
          - name: event_id
            type: INTEGER
          - name: user_id
            type: INTEGER
          - name: event_type
            type: VARCHAR
          - name: event_timestamp
            type: TIMESTAMP

      transactions:
        description: Transaction events with timestamps and amounts
        columns:
          - name: transaction_id
            type: INTEGER
            description: Unique transaction identifier
          - name: user_id
            type: INTEGER
            description: User who made the transaction
          - name: amount
            type: DECIMAL(10,2)
            description: Transaction amount
          - name: transaction_timestamp
            type: TIMESTAMP
            description: When the transaction occurred
          - name: transaction_type
            type: VARCHAR
            description: Type of transaction (purchase, refund, etc.)
